load "ricer4/model/exceptions.rb"
load "ricer4/model/scope.rb"
load "ricer4/model/server.rb"
load "ricer4/model/channel.rb"
load "ricer4/model/plugin.rb"
load "ricer4/model/permission.rb"
load "ricer4/model/parameter.rb"
